services:
  database:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    ports:
      - 3307:3306
    #volumes:
    #  - ./.docker/dbdata:/var/lib/mysql
  app:
    build: ./Caticket.PartnerAPI
    ports:
      - 5000:5000
    volumes:
      - ./Caticket.PartnerAPI:/home/dotnet/app