services:
  partner-db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    ports:
      - 3307:3306
    #volumes:
    #  - ./.docker/partner-dbdata:/var/lib/mysql

  partner-app:
    build: ./Caticket.PartnerAPI
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./Caticket.PartnerAPI:/home/dotnet/app
    depends_on:
      partner-db:
        condition: service_healthy

  sales-db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
    ports:
      - 3308:3306
    #volumes:
    #  - ./.docker/sales-dbdata:/var/lib/mysql
    
  auth-db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    ports:
      - 3309:3306
    #volumes:
    #  - ./.docker/sales-dbdata:/var/lib/mysql

  sales-app:
    build: ./Caticket.SalesAPI
    ports:
      - 5002:5000
    volumes:
      - ./Caticket.SalesAPI:/home/dotnet/app
    depends_on:
      sales-db:
        condition: service_healthy

  front-end:
    build: ./caticket
    ports:
      - 3000:3000
    volumes:
      - ./caticket:/home/next/app
    # depends_on:
    #   sales-app:
    #     condition: service_healthy
    #   partner-app:
    #     condition: service_healthy
