GET http://localhost:5196/events
###
# @name createEvent
POST http://localhost:5196/events
Content-Type: application/json

{
    "name": "fff",
    "price": 0,
    "date": "2024-07-25T20:30:00"
}

###
PATCH http://localhost:5196/events
Content-Type: application/json

{   
    "id": "3d7f658d-812e-4dae-bcd3-b33090925a2e",
    "name": "bbb",
    "price": 32.99,
    "description": "Some desc",
    "date": "2024-07-28T22:22:00"
}

###
DELETE http://localhost:5196/events
Content-Type: application/json

{
    "id": "56b883cc-270f-4f35-a6e5-c9cf7bef984c"
}

@eventId = {{ createEvent.response.body.id }}

###
# @name createSpot
GET http://localhost:5196/events/{{eventId}}/spots

###
POST http://localhost:5196/events/{{eventId}}/spots
Content-Type: application/json

{
    "name": "B3"
}