@partner1 = 951234d4-e886-472d-898c-4e578a152e28
@partner2 = a6dc1b76-21cc-405a-aecf-b8ed6657e3ff
@partnerNone = 

GET http://localhost:5000/all-events

###
GET http://localhost:5000/events
X-TenantId: {{partner2}}

###
# @name createEvent
POST http://localhost:5000/events
X-TenantId: {{partner2}}
Content-Type: application/json

{
    "name": "fff",
    "price": 0,
    "date": "2024-07-25T20:30:00"
}

###
PATCH http://localhost:5000/events
X-TenantId: {{partner2}}
Content-Type: application/json

{   
    "id": "39e9a85d-26ea-4a31-8a3f-ae07e0d2ac19",
    "name": "bbb",
    "price": 32.99,
    "description": "Some desc",
    "date": "2024-07-28T22:22:00"
}

###
DELETE http://localhost:5000/events
X-TenantId: {{partner2}}
Content-Type: application/json

{   
    "id": "8c14b36a-6fc8-4996-a459-1601598ad0ac"
}

###
@eventId = {{ createEvent.response.body.id }}

###
# @name createSpot
GET http://localhost:5000/events/{{eventId}}/spots
X-TenantId: {{partner2}}

###
POST http://localhost:5000/events/{{eventId}}/spots
X-TenantId: {{partner2}}
Content-Type: application/json

{
    "name": "B1"
}

###
POST http://localhost:5000/events/{{eventId}}/spots/reserve
X-TenantId: {{partner2}}
Content-Type: application/json

{
    "spots": ["A1"],
    "email": "a@a.com",
    "ticketKind": 1
}