GET http://localhost:5196/event
###
POST http://localhost:5196/event
Content-Type: application/json

{
    "name": "b",
    "price": 0,
    "date": "2024-07-25T20:30:00"
}

###
PATCH http://localhost:5196/event
Content-Type: application/json

{
    "id": "56b883cc-270f-4f35-a6e5-c9cf7bef984c",
    "name": "bbb",
    "price": 32.99,
    "description": "Some desc",
    "date": "2024-07-28T22:22:00"
}

###
DELETE http://localhost:5196/event
Content-Type: application/json

{
    "id": "56b883cc-270f-4f35-a6e5-c9cf7bef984c"
}