GET http://localhost:5000/all-events
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDAwMjJiOS02YmRiLTQyMWEtYmNmMC03NTNkNDBmODAzZmUiLCJlbWFpbCI6IlRlc3RlQFRlc3RlLmNvbSIsImp0aSI6IjMwZjE3MTE1LWEyOGQtNDIzMi1iNmNlLWY0NDFmN2FhZGY4YiIsIm5iZiI6MTcyMjg2ODA4NCwiaWF0IjoiMDgvMDUvMjAyNCAxNToyODowNCIsInJvbGUiOiJwYXJ0bmVyIiwiZXhwIjoxNzIyODcxNjg0LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0IiwiYXVkIjoiQXVkaWVuY2UifQ.dh6HamtmHmM0F7S4uVwaW3-O1r2RyOertFZBw5YZK53mKeIYBQXj3Fn9gKDi5MOu7Qn2rrHD5Mfu5FQqZnWqRA

###
POST http://localhost:5000/register/partner
Content-Type: application/json

{
    "email": "Teste@Teste.com",
    "name": "Teste",
    "password": "Teste@1",
    "confirmPassword": "Teste@1"
}

###
POST http://localhost:5000/register/user
Content-Type: application/json

{
    "email": "User@User.com",
    "name": "User",
    "password": "User@1",
    "confirmPassword": "User@1"
}

###
# @name login 
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "Teste@Teste.com",
    "password": "Teste@1"
}

###
GET http://localhost:5000/test
Authorization: Bearer {{ login.response.body.token }}