POST http://localhost:5107/register/partner
Content-Type: application/json

{
    "email": "Teste@Teste.com",
    "name": "Teste",
    "password": "Teste@1",
    "confirmPassword": "Teste@1"
}

###
POST http://localhost:5107/register/user
Content-Type: application/json

{
    "email": "User@User.com",
    "name": "User",
    "password": "User@1",
    "confirmPassword": "User@1"
}

###
# @name login 
POST http://localhost:5107/login
Content-Type: application/json

{
    "email": "User@User.com",
    "password": "User@1"
}

###
GET http://localhost:5107/test
Authorization: Bearer {{ login.response.body.token }}