POST http://localhost:5107/register/partner
Content-Type: application/json

{
    "email": "Teste@Teste.com",
    "name": "Teste",
    "password": "Teste@1",
    "confirmPassword": "Teste@1"
}

###
# @name login 
POST http://localhost:5107/login
Content-Type: application/json

{
    "email": "Partner@Partner.com",
    "password": "Partner@1"
}

###
GET http://localhost:5107/test
Authorization: Bearer {{ login.response.body.token }}